Pop upp data
GloireIrenge/My_Portfolio pull request #13
Opened 2022-07-19 19:16 UTC by GloireIrenge

:notebook:**This pull request is done after implementing the following functionalities:**

- When the user clicks the button to check project details, the popup with details about the project appears.
- When the user clicks the close (X) button, the popup disappears.
- The project is made for both mobile :iphone: and desktop :computer: screen sizes.
- The pieces of data are stored in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, and link to the source.
- The main page is updated so that the projects section is created dynamically using the information stored in that JavaScript object. 

**Contributor** :technologist:
@RiyaBulia12

2022-07-19 20:32 UTC, codecaiine requested changes
Hi @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
- No linters errors :heavy_check_mark:  

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 20:32 UTC, codecaiine commented on JS/localStorage.js
> +};
- [ ] On the desktop version we click or tap the **close (X) button,** and the popup disappear. Good job so far :clap: But it is not working for the mobile version please fix it to give your user a great user experience :smile:

2022-07-19 20:32 UTC, codecaiine commented on JS/localStorage.js
> +};
- [ ] Good job so far your popup is displaying :+1: But it is not working as expected :cry:  For Desktop your popup does not conform to the dimensions set in the Figma template. You can see a difference when you compare it to Figma. Please use the dimensions and follow the layout as defined in the Figma template to make them similar. :smile: 

### Figma template
![Screenshot from 2022-07-19 19-31-42](https://user-images.githubusercontent.com/6615394/179837220-be1e4a1c-4449-4f77-bccd-e6be8dc2abff.png)

### Your project
![Screenshot from 2022-07-19 19-31-13](https://user-images.githubusercontent.com/6615394/179837229-4eb01122-5443-4dd4-96da-61efec4d6a70.png)




- [ ] For the Mobile version the details about the project do not appear. The elements are improperly placed as you can see in the picture below :disappointed: Please fix it so they can appear on the popup so it looks similar to the Figma template. :+1: 

### Your Mobile popup
![Screenshot from 2022-07-19 19-32-53](https://user-images.githubusercontent.com/6615394/179838258-3ab660a1-bd95-4cbb-b890-b7fdf794ea72.png)

### Figma mobile popup
![Screenshot from 2022-07-19 19-32-11](https://user-images.githubusercontent.com/6615394/179838263-04791119-846a-4d81-99a6-496ed91d626f.png)

2022-07-20 15:24 UTC, ShahierNashaat requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 15:24 UTC, ShahierNashaat commented on CSS/modal.css
> +  position: fixed;
- [ ] Please make the position `absolute` instead of `fixed` as you can when the user scrolls down the title goes over the image.
- [ ] Also the buttons for `See Live` and `See Source` should be beside each other.

![Screenshot from 2022-07-20 17-21-39](https://user-images.githubusercontent.com/33752735/180020478-1cb0da84-2e55-4091-b9d7-24495263dfc3.png)

2022-07-20 16:46 UTC, Nemwel-Boniface approved these changes
## Hello @GloireIrenge               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  


Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 16:50 UTC, merged