Desktop features
GloireIrenge/My_Portfolio pull request #6
Opened 2022-07-08 09:16 UTC by GloireIrenge

In this pull request I:
- Edit the portfolio mobile version and make it responsive desktop version
- Add some animations
- Make the Dekstop version looks like the Figma template

2022-07-08 11:05 UTC, NgozikaNwocha requested changes

2022-07-08 11:05 UTC, GoddessNgozi commented on index.html
>          <div class="body-class">
Header should contain logo and top navigational links. Please remove the h1, span, p and social icons.

2022-07-08 11:05 UTC, GoddessNgozi commented on index.html
>          <div class="body-class">
<img width="449" alt="Screenshot 2022-07-08 at 11 50 09" src="https://user-images.githubusercontent.com/51258047/177978532-d09b6abc-ceef-43cb-a5eb-641f135274da.png">

Works section should be placed inside of the main tag. Important sections in a website are placed inside a main tag.

2022-07-08 11:05 UTC, NgozikaNwocha commented on index.html
>          <div class="body-class">
<img width="566" alt="Screenshot 2022-07-08 at 11 58 13" src="https://user-images.githubusercontent.com/51258047/177979625-a2519ee5-3d33-40fc-878c-594d1743b217.png">

Kindly place the My_footer div inside of a footer tag. It is important to use semantic tags to section your work for good/readability, for screen readers and SEO.

2022-07-09 15:44 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @GloireIrenge,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-09 15:44 UTC, topeogunleye commented on main.css
> +@media screen and (max-width: 980px) {
- [ ] I kindly suggest that you make your project styling mobile-first. That would mean that you need to use `min-width` to style for desktops and not `max-width` to style for mobile.

2022-07-09 15:44 UTC, topeogunleye commented on index.html
> +            <article class="featured">
- [ ] I kindly suggest that you add your `see project` button that takes you to the Live Demo of the featured project or to the GitHub repository.

| Your Design  | Template Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/52934128/178112208-d8813be9-7aef-4d73-8023-77a7bb93911d.png) |  ![image](https://user-images.githubusercontent.com/52934128/178112159-ce45e9d9-9a8d-4c58-bf5c-07f08fa109ba.png)|

2022-07-09 15:44 UTC, topeogunleye commented on index.html
> -                    <div class="multi-post2">
- [ ] As written in the project requirements. I kindly suggest that you ensure that when a project is hovered on with the mouse:
-  the description and dark opacity disappear
-  and a See Project button appears to the bottom of the image and takes the whole image width.
-   Your `See Project` button should link to the Live Demo of the project or to the GitHub repository.

- [ ] [OPTIONAL] Please ensure that your padding for your project is similar to the template design. Kindly see the images below

| Your Design  |Template Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/52934128/178112591-2aecddbf-19ab-4b28-a88f-dd7f7596991d.png) | ![image](https://user-images.githubusercontent.com/52934128/178112550-f1b33dc5-838e-4251-898a-ea299dc20431.png) |

2022-07-09 19:24 UTC, merged